name: Push to https://bmltsearch.bmlt.app

on:
  push:
    branches: ['version_5']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Script for browser
        run: ionic build --prod --source-map --platform=browser

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'www'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
